platform :ios, '10.0'



target 'SwiftAssignment' do
  inhibit_all_warnings!
  use_frameworks!

  # Pods for SwiftAssignment
    pod 'Alamofire', '~> 4.2.0'
    pod 'AlamofireObjectMapper', '~> 4.0'
  


  target 'SwiftAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftAssignmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
